// USER ACTIONS

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const LOGOUT_USER = "LOGOUT_USER";

export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAILURE = "EDIT_PROFILE_FAILURE";

export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE";

export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILURE = "GET_ALL_USERS_FAILURE";

// POST ACTIONS

export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAILURE = "ADD_POST_FAILURE";

export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_FAILURE = "EDIT_POST_FAILURE";

// GROUP ACTIONS

export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_FAILURE = "CREATE_GROUP_FAILURE";

export const DELETE_GROUP_SUCCESS = "DELETE_GROUP_SUCCESS";
export const DELETE_GROUP_FAILURE = "DELETE_GROUP_FAILURE";

export const EDIT_GROUP_SUCCESS = "EDIT_GROUP_SUCCESS";
export const EDIT_GROUP_FAILURE = "EDIT_GROUP_FAILURE";

export const FETCH_GROUPS_SUCCESS = "FETCH_GROUPS_SUCCESS";
export const FETCH_GROUPS_FAILURE = "FETCH_GROUPS_FAILURE";

export const FETCH_SINGLE_GROUP_SUCCESS = "FETCH_SINGLE_GROUP_SUCCESS";
export const FETCH_SINGLE_GROUP_FAILURE = "FETCH_SINGLE_GROUP_FAILURE";

export const JOIN_GROUP_SUCCESS = "JOIN_GROUP_SUCCESS";
export const LEAVE_GROUP_SUCCESS = "LEAVE_GROUP_SUCCESS";

export const JOIN_GROUP_FAILURE = "JOIN_GROUP_FAILURE";
export const LEAVE_GROUP_FAILURE = "LEAVE_GROUP_FAILURE";

export const ADD_GROUP_POST_SUCCESS = "ADD_GROUP_POST_SUCCESS";
export const ADD_GROUP_POST_FAILURE = "ADD_GROUP_POST_FAILURE";

export const DELETE_GROUP_POST_SUCCESS = "DELETE_GROUP_POST_SUCCESS";
export const DELETE_GROUP_POST_FAILURE = "DELETE_GROUP_POST_FAILURE";

//FRIEND ACTIONS

export const ADD_FRIEND_SUCCESS = "ADD_FRIEND_SUCCESS";
export const ADD_FRIEND_FAILURE = "ADD_FRIEND_FAILURE";

export const DELETE_FRIEND_SUCCESS = "DELETE_FRIEND_SUCCESS";
export const DELETE_FRIEND_FAILURE = "DELETE_FRIEND_FAILURE";
